CREATE TABLE equipment_rentals (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    rental_number        VARCHAR(20) UNIQUE,
    renter_id            BIGINT NOT NULL,
    reviewed_by          BIGINT,
    status               ENUM('PENDING_REVIEW','APPROVED','REJECTED','CANCELLED',
                              'PENDING_PAYMENT','PENDING_CASH','PAID','ACTIVE','OVERDUE','RETURNED') NOT NULL,
    payment_method       ENUM('NONE','ONLINE','CASH') NOT NULL DEFAULT 'NONE',
    payment_status       ENUM('NONE','ONLINE_PENDING','ONLINE_PAID','CASH_PENDING','CASH_CONFIRMED') NOT NULL DEFAULT 'NONE',
    requested_start_date DATE NOT NULL,
    requested_end_date   DATE NOT NULL,
    approved_start_date  DATE,
    approved_end_date    DATE,
    duration_days        INT,
    total_base_amount    BIGINT,
    total_penalty_amount BIGINT DEFAULT 0,
    total_amount         BIGINT,
    rejection_reason     TEXT,
    committee_notes      TEXT,
    renter_notes         TEXT,
    approved_at          DATETIME,
    paid_at              DATETIME,
    active_at            DATETIME,
    returned_at          DATETIME,
    due_return_date      DATE,
    created_at           DATETIME NOT NULL,
    updated_at           DATETIME NOT NULL,
    FOREIGN KEY (renter_id)   REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id)
);
