CREATE TABLE payments (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    equipment_rental_id   BIGINT NOT NULL UNIQUE,
    user_id               BIGINT NOT NULL,
    bill_id               VARCHAR(50),
    collection_id         VARCHAR(50),
    amount                BIGINT NOT NULL,
    paid_amount           BIGINT,
    payment_type          ENUM('ONLINE','CASH') NOT NULL,
    status                ENUM('PENDING','PAID','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
    paid_at               DATETIME,
    due_at                DATE,
    payment_channel       VARCHAR(50),
    transaction_id        VARCHAR(100),
    transaction_status    VARCHAR(50),
    bill_url              VARCHAR(500),
    confirmed_by          BIGINT,
    confirmed_at          DATETIME,
    created_at            DATETIME NOT NULL,
    updated_at            DATETIME NOT NULL,
    FOREIGN KEY (equipment_rental_id) REFERENCES equipment_rentals(id),
    FOREIGN KEY (user_id)             REFERENCES users(id),
    FOREIGN KEY (confirmed_by)        REFERENCES users(id)
);
